EatZilla/Controllers/DishController.cs
using EatZilla.Models.CoreClasses;
using EatZilla.Models.DataConnection;
using Microsoft.AspNetCore.Mvc;

namespace EatZilla.Controllers
{
    public class DishController : Controller


    {
        public static int dishid = 1003;
        private readonly ApplicationDatabaseContext data;

        public DishController(ApplicationDatabaseContext db) {

            data = db;
        }


        public IActionResult Index()
        {
            List<Dish> dish = data.dishes.ToList();
            return View(dish);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(String dishname,String price)
        {
            int p = Convert.ToInt32(price);
            Dish dish = new Dish(dishid++,dishname,p);

            data.dishes.Add(dish);
            data.SaveChanges();

            return RedirectToAction("Index");


        }
        
    }
}

EatZilla/Controllers/ResturantController.cs
using EatZilla.Models.CoreClasses;
using EatZilla.Models.DataConnection;
using Microsoft.AspNetCore.Mvc;

namespace EatZilla.Controllers
{
    public class ResturantController : Controller

    {
        private readonly ApplicationDatabaseContext data;

        public ResturantController(ApplicationDatabaseContext db)
        {
            data = db;
            
        }

        public IActionResult Index()

        {
            List<Resturant> list = data.resturants.ToList();
            
            return View(list);
        }
    }
}

EatZilla/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EatZilla.Models.CoreClasses;
using EatZilla.Models.DataConnection;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;

namespace EatZilla.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDatabaseContext _context;
        public static int Uid = 1016; 

        public UsersController(ApplicationDatabaseContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       public IActionResult Create(String Name,String Email,String Phone,String Password)

        {
            User u = new User(Uid++,Name,Email,Phone,Password);
            _context.Add(u);
            _context.SaveChanges();

            return RedirectToAction("Sucess");
        }
        public IActionResult Sucess()
        {
            return View();
        }




        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Phone,Password")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(String Email,String Password)
        {
            List<User> users = _context.Users.ToList();
            foreach (User x in users)
            {
                if(x.Email.Equals(Email) && x.Password.Equals(Password)){
                    Console.WriteLine("Hello World");
                    return RedirectToAction("LoginSucess");
                }
                

            }
            return RedirectToAction("Create");

           
        }
        public IActionResult LoginSucess()
        {
            return View();
        }
    }
}

EatZilla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EatZilla</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/superhero.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EatZilla.styles.css" asp-append-version="true" />

   <style>
        .carousel-item img {
            width: 100%;
            height: auto;
        }
       

        .navbg {
/*             background-color: #ffa54f !important;
 */            background-image:none !important;
    background:transparent !important;
        }
   </style>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbg navbar-toggleable-sm  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EatZilla</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="OrderFood">Order Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resturant" asp-action="index">All Resturants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
      @*   <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="10000">
                    <img width="100vw" src="./lib/images/image3.png" class="d-block img w-100" alt="...">
                </div>
                <div class="carousel-item" data-bs-interval="2000">
                    <img src="./lib/images/image1.png" class="d-block img w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="./lib/images/image2.png" class="d-block img w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div> *@
        



        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EatZilla - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>